name: Pages
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: ./build.sh
        env:
          GH_ENGINIRO_TOKEN: ${{ secrets.GH_ENGINIRO_TOKEN }}
      - run: touch build/site/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/site/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4