name: Pages
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: ./build.sh
      - run: touch build/site/.nojekyll
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/site/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1